appattributes:
  api.version: v1
  baseurl: /api/${appattributes.api.version}
  deadLine: 11:00:00

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20

  datasource:
    url: jdbc:h2:mem:restrating
    username: sa
    password: password

  h2.console.enabled: true

  data.rest:
    basePath: ${appattributes.baseurl}
    returnBodyOnCreate: true
