appattributes:
  api.version: v1
  baseurl: /api/${appattributes.api.version}

spring:
  messages:
    basename: messages
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  #        cache:
  #          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  #          use_query_cache: false
  #          use_second_level_cache: true
  cache:
    jcache:
      config: classpath:ehcache.xml

  datasource:
    url: jdbc:h2:mem:restrating
    username: sa
    password: password

  h2.console.enabled: true

  data.rest:
    basePath: ${appattributes.baseurl}
    returnBodyOnCreate: true
